services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: chat01
      POSTGRES_PASSWORD: chat01senha
      POSTGRES_DB: chat01
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always

  backend:
    build: ./backend
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: ${NODE_ENV}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      PROXY_PORT: ${PROXY_PORT}
      PORT: ${PORT}

      DB_DIALECT: ${DB_DIALECT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}

      REDIS_URI: ${REDIS_URI}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: ${REACT_APP_BACKEND_URL}
    restart: always
    depends_on:
      - backend

volumes:
  postgres_data:
